language: php

sudo: false

addons:
  firefox: "47.0.1"
  postgresql: "9.3"
  apt:
    packages:
      - oracle-java8-installer
      - oracle-java8-set-default

cache:
  directories:
    - $HOME/.composer/cache
    - $HOME/.npm

php:
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
 - 5.6
=======
>>>>>>> MOODLE_34_STABLE
=======
 - 5.6
>>>>>>> MOODLE_34_STABLE
=======
>>>>>>> MOODLE_34_STABLE
 - 7.0
 - 7.1

env:
<<<<<<< HEAD
 matrix:
<<<<<<< HEAD
<<<<<<< HEAD
  - DB=mysqli MOODLE_BRANCH=MOODLE_32_STABLE
  - DB=pgsql MOODLE_BRANCH=MOODLE_32_STABLE
=======
  - DB=mysqli MOODLE_BRANCH=MOODLE_33_STABLE
  - DB=pgsql MOODLE_BRANCH=MOODLE_33_STABLE
>>>>>>> MOODLE_33_STABLE
=======
  - DB=mysqli MOODLE_BRANCH=MOODLE_34_STABLE
  - DB=pgsql MOODLE_BRANCH=MOODLE_34_STABLE
>>>>>>> MOODLE_34_STABLE

=======
  global:
    - MOODLE_BRANCH=MOODLE_34_STABLE
  matrix:
    - DB=mysqli
    - DB=pgsql
>>>>>>> MOODLE_34_STABLE
=======
 - 7.1
 - 7.2

env:
  global:
    - MOODLE_BRANCH=MOODLE_35_STABLE
  matrix:
    - DB=mysqli
    - DB=pgsql
>>>>>>> MOODLE_35_STABLE

before_install:
  - phpenv config-rm xdebug.ini
  - nvm install 8.9
  - nvm use 8.9
  - cd ../..
  - composer create-project -n --no-dev moodlerooms/moodle-plugin-ci ci ^2
  - export PATH="$(cd ci/bin; pwd):$(cd ci/vendor/bin; pwd):$PATH"

install:
  - moodle-plugin-ci add-plugin --branch $MOODLE_BRANCH vfremaux/moodle-format_page
  - moodle-plugin-ci install

script:
  - moodle-plugin-ci phplint
  - moodle-plugin-ci phpcpd
  - moodle-plugin-ci phpmd
  - moodle-plugin-ci codechecker
  - moodle-plugin-ci validate
  - moodle-plugin-ci savepoints
  - moodle-plugin-ci mustache
  - moodle-plugin-ci grunt
  - moodle-plugin-ci phpunit
#  - moodle-plugin-ci behat
